# Required
baseURL = "https://tinydevcrm.com"
languageCode = "en-us"
title = "TinyDevCRM"
theme = "tinydevcrm"

# Optional
googleAnalytics = "UA-128189162-2"

[menu]
# Navbar items
[[menu.nav]]
name = "TinyDevCRM"
url = "/"
weight = 1
[[menu.nav]]
# name = "Dashboard"
# url = "https://dashboard.tinydevcrm.com"
name = "Dashboard (Coming Soon)"
url = "/"
weight = 2
[[menu.nav]]
# name = "API"
# url = "https://api.tinydevcrm.com"
name = "API (Coming Soon)"
url = "/"
weight = 3
[[menu.nav]]
# name = "Docs"
# url = "https://docs.tinydevcrm.com"
name = "Docs (Coming Soon)"
url = "/"
weight = 4
[[menu.nav]]
# name = "Blog"
# url = "https://blog.tinydevcrm.com"
name = "Blog (Coming Soon)"
url = "/"
weight = 5
[[menu.nav]]
name = "Code"
url = "https://github.com/yingw787"


[params]
    # Required #
    author = "Ying Wang"
    email = "me@yingw787.com"
    description = "TinyDevCRM"
    copyrightYear = "2020"
    favicon = "img/favicon.png"
    mailchimpURL = "https://yingw787.us16.list-manage.com/subscribe/post?u=5280d2de8e3d00fba39c1f4b3&amp;id=2a7decb380"
    mailchimpBotDecoyLink = "b_5280d2de8e3d00fba39c1f4b3_2a7decb380"

    # Navbar #
    firstElementText = "TinyDevCRM"
    firstElementHref = "/"
    thirdElementText = "Dashboard"
    thirdElementHref = "https://dashboard.tinydevcrm.com"

    # Optional #
    font = "Space Mono" # Available fonts include: ["Space Mono"].
    bodyTextColor = "#839496" # Solarized Base0
    backgroundColor = "#002b36" # Solarized Base03

    formInputColor = "#eee8d5"
    formBackgroundColor = "#586e75"
    formSelectedColor = "#eee8d5"

    buttonColor = "#eee8d5"
    buttonBackgroundColor = "#586e75"

    footerTextColor = "#586e75"
