# Required
baseURL = "https://tinydevcrm.com"
languageCode = "en-us"
title = "TinyDevCRM"
theme = "carrd50"

# Optional
googleAnalytics = "UA-128189162-2"

[params]
    # Required #
    author = "Ying Wang"
    email = "me@yingw787.com"
    description = "TinyDevCRM - Coming Soon"
    copyrightYear = "2020"
    favicon = "img/favicon.png"
    mailchimpURL = "https://yingw787.us16.list-manage.com/subscribe/post?u=5280d2de8e3d00fba39c1f4b3&amp;id=2a7decb380"
    mailchimpBotDecoyLink = "b_5280d2de8e3d00fba39c1f4b3_2a7decb380"

    # Optional #
    font = "Space Mono" # Available fonts include: ["Space Mono"].
    titleImage = "img/image01.png"
    titleTextColor = "#eee8d5"
    bodyTextColor = "#eee8d5" # Solarized Base2
    backgroundColor = "#586e75" # Solarized Base01

    formInputColor = "#666666"
    formBackgroundColor = "#eee8d5"
    formSelectedColor = "#1ABC9C"

    buttonColor = "#eee8d5"
    buttonBackgroundColor = "#3BACFF"

    footerTextColor = "#eee8d5"
